server:
  port: 8761

spring:
  application:
    name: getRand_server

# ?????? ??? ???? ??(??? true)
# ??? ??? ?? ??? ?????? ???? ???. ?? ???? ??? ??? ?? ???
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

  # enable-self-preservation ??? ???? ???? ?????? ???? ?? ???? ??
  # false ? ???? ????? ???? ??? ?? ??
  # ?? ???? ???? ???? ???? ?? ??
  server:
    #    eviction-interval-timer-in-ms: 3000
    enable-self-preservation: false
